name: Deploy Storybook

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - master

jobs:
    deploy:
        name: Build & deploy Storybook to GitHub Pages
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci --legacy-peer-deps

            - name: Run tests
              run: npm run test

            - name: Build Storybook
              run: npm run storybook:build

            - name: Deploy Storybook to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: gh-pages
                  build_dir: storybook-static
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
