name: Deploy Storybook to Github pages
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    release:
        name: Deploy Storybook to Github pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.17'
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Run tests
              run: yarn run test
            - name: Build storybook
              run: yarn run storybook:build
            - name: Deploy storybook
              uses: crazy-max/ghaction-github-pages@v1
              with:
                  target_brach: gh-pages
                  build_dir: storybook-static
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
